import Link from 'next/link';
import Layout from '../../components/Layout';
import styles from '../../styles/Insights.module.css';

const content = {
  'digitalization-roadmap': { category: 'Business digitalization', title: 'Where should a growing business start with digitalization?', intro: 'Digitalization works best when it starts with a business constraint, not a technology trend.', sections: [['Start with the work', 'Look for repeated handoffs, duplicated data entry, slow approvals, and decisions that depend on one person. These are signals that a process can be made clearer and more resilient.'], ['Choose the smallest useful step', 'A good first project creates visible value without attempting to rebuild the entire business. A focused workflow, shared data view, or customer portal can become the foundation for what comes next.'], ['Keep the system adaptable', 'The right solution may combine existing software, a database, cloud services, automation, and custom code. The goal is a practical system that can grow with the business.']] },
  'process-optimization': { category: 'Process optimization', title: 'Why better processes come before better software', intro: 'Automating a confusing process only makes confusion move faster. Clarity is the first optimization.', sections: [['See the complete journey', 'Map what actually happens, including exceptions, rework, waiting, and the information people need at each step. The real process is often different from the documented one.'], ['Remove friction before adding tools', 'Small changes to ownership, approval rules, or data capture can create more value than a large software implementation. Simplify the work before you automate it.'], ['Measure the change', 'Choose a small set of meaningful signals such as cycle time, error rate, or hours returned to the team. Improvement becomes easier to sustain when it can be seen.']] },
  'data-integration': { category: 'Data and integrations', title: 'Make business data work across the systems you already use', intro: 'Your business does not need one giant system. It needs dependable connections between the systems that matter.', sections: [['Find the source of truth', 'Identify where important information is created, which system owns it, and where people currently copy it by hand. This is the starting point for a reliable data flow.'], ['Connect deliberately', 'APIs, database views, scheduled jobs, event-driven workflows, and lightweight custom services can all be appropriate. The architecture should match the size and risk of the problem.'], ['Design for people', 'Good integration is not only technical. It gives teams timely, consistent information in the tools and views they already use to make decisions.']] },
};

export async function getStaticPaths() { return { paths: Object.keys(content).map((slug) => ({ params: { slug } })), fallback: false }; }
export async function getStaticProps({ params }) { return { props: { article: content[params.slug] } }; }

export default function Insight({ article }) {
  return <Layout><main className={styles.articlePage}><Link className={styles.backLink} href="/insights">↖ All insights</Link><p className={styles.eyebrow}><span /> {article.category}</p><h1>{article.title}</h1><p className={styles.articleIntro}>{article.intro}</p><div className={styles.articleBody}>{article.sections.map(([heading, text]) => <section key={heading}><h2>{heading}</h2><p>{text}</p></section>)}</div><Link className={styles.contactLink} href="/contact">Discuss a solution <span>↗</span></Link></main></Layout>;
}